barentswatch.auth.client-id=trytson.wielki@gmail.com:ais-app
barentswatch.auth.client-secret=zaq12wsxcde3
barentswatch.auth.scope=ais
barentswatch.auth.grant-type=client_credentials
barentswatch.auth.token-uri=https://id.barentswatch.no/connect/token